### ISSUE TITLE
Generate with licence

### ISSUE THREAD

**Issue by CrimsonNynja** [CrimsonNynja/generator-node-graphql#51]
Currently when generating a project, the console will throw a warning message that no licence is included in the package.json.

```
warning package.json: No license field
warning No license field
```

This task aims to resolve that by setting a default licence to that of MIT.

**Comment by gitrahulgit** [comment]
I would like to work on it!!

**Comment by CrimsonNynja** [comment]
@gitrahulgit sounds good, have assigned you the task

**Comment by haruelrovix** [comment]
Hey @gitrahulgit 👋  Do you still work on this issue?

**Comment by CrimsonNynja** [comment]
@haruelrovix if you dont get a response soon, feel free to take this as hacktoberfest is almost up.
